import Link from 'next/link';

export default function Home() {
  const navItems = [
    { name: 'Home', href: '/' },
    { name: 'Training', href: '/training' },
    { name: 'Pricing', href: '#pricing' }
  ];

  return (
    <main className="min-h-screen bg-[#0a192f] text-white">
      <nav className="p-6 flex justify-center gap-8">
        {navItems.map((item) => (
          <Link key={item.name} href={item.href} className="hover:text-green-400 transition-colors">
            {item.name}
          </Link>
        ))}
      </nav>
      <section className="py-12 bg-[#112240] mt-10"> <div className="max-w-4xl mx-auto px-4"> <h2 className="text-2xl font-bold text-green-400 mb-6 text-center">My Core Expertise</h2> <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center"> <div className="p-4 border border-gray-700 rounded-xl">🚀 Data Entry</div> <div className="p-4 border border-gray-700 rounded-xl">⌨️ Fast Typing</div> <div className="p-4 border border-gray-700 rounded-xl">📄 PDF Conversion</div> <div className="p-4 border border-gray-700 rounded-xl">🤖 AI Solutions</div> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      <section className="py-12 bg-[#0a192f] border-y border-gray-800"> <div className="max-w-4xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-8 text-center"> <div> <p className="text-3xl font-bold text-green-400">100+</p> <p className="text-gray-400 text-sm">Projects Done</p> </div> <div> <p className="text-3xl font-bold text-blue-400">99%</p> <p className="text-gray-400 text-sm">Accuracy</p> </div> <div> <p className="text-3xl font-bold text-purple-400">24/7</p> <p className="text-gray-400 text-sm">Support</p> </div> <div> <p className="text-3xl font-bold text-yellow-400">5.0</p> <p className="text-gray-400 text-sm">Fiverr Rating</p> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      <section className="py-16 px-4"> <h2 className="text-3xl font-bold text-center mb-12">How I Deliver Results</h2> <div className="max-w-5xl mx-auto grid md:grid-cols-3 gap-8"> <div className="p-6 bg-[#112240] rounded-2xl border-t-4 border-green-500"> <h3 className="text-xl font-bold mb-2">1. Analyze</h3> <p className="text-gray-400">Requirements ko achi tarah samajhna taake mistake na ho.</p> </div> <div className="p-6 bg-[#112240] rounded-2xl border-t-4 border-blue-500"> <h3 className="text-xl font-bold mb-2">2. Execute</h3> <p className="text-gray-400">100% accuracy aur fast speed ke sath kaam mukammal karna.</p> </div> <div className="p-6 bg-[#112240] rounded-2xl border-t-4 border-purple-500"> <h3 className="text-xl font-bold mb-2">3. Deliver</h3> <p className="text-gray-400">On-time delivery aur revision support taake aap satisfy hon.</p> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      <section className="py-12 bg-[#0a192f] border-y border-gray-800"> <div className="max-w-4xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-8 text-center"> <div> <p className="text-3xl font-bold text-green-400">100+</p> <p className="text-gray-400 text-sm">Projects Done</p> </div> <div> <p className="text-3xl font-bold text-blue-400">99%</p> <p className="text-gray-400 text-sm">Accuracy</p> </div> <div> <p className="text-3xl font-bold text-purple-400">24/7</p> <p className="text-gray-400 text-sm">Support</p> </div> <div> <p className="text-3xl font-bold text-yellow-400">5.0</p> <p className="text-gray-400 text-sm">Fiverr Rating</p> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      
      <div className="flex flex-col items-center justify-center pt-20 px-4 text-center">
        <h1 className="text-5xl font-bold mb-4">GlobalSkill.pk</h1>
        <p className="text-xl text-gray-400 mb-8">Best AI Skill Learning Platform in Pakistan</p>
        <Link href="/training" className="bg-green-500 hover:bg-green-600 text-black px-8 py-3 rounded-full font-bold transition-all">
          Start Training - Rs. 499
        </Link>
      </div>
      <section className="py-8 bg-[#0a192f] border-t border-gray-800"> <div className="max-w-4xl mx-auto px-4 flex justify-around items-center"> <div className="text-center"> <p className="text-gray-400 text-sm">Ethereum (ETH)</p> <p className="text-xl font-bold text-blue-400">Trading Live</p> </div> <div className="h-10 w-[1px] bg-gray-700"></div> <div className="text-center"> <p className="text-gray-400 text-sm">Solana (SOL)</p> <p className="text-xl font-bold text-purple-400">Market Active</p> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      <section className="py-12 bg-[#0a192f] border-y border-gray-800"> <div className="max-w-4xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-8 text-center"> <div> <p className="text-3xl font-bold text-green-400">100+</p> <p className="text-gray-400 text-sm">Projects Done</p> </div> <div> <p className="text-3xl font-bold text-blue-400">99%</p> <p className="text-gray-400 text-sm">Accuracy</p> </div> <div> <p className="text-3xl font-bold text-purple-400">24/7</p> <p className="text-gray-400 text-sm">Support</p> </div> <div> <p className="text-3xl font-bold text-yellow-400">5.0</p> <p className="text-gray-400 text-sm">Fiverr Rating</p> </div> </div> </section>
      <section className="py-20 bg-[#0a192f]"> <div className="max-w-6xl mx-auto px-4"> <h2 className="text-3xl font-bold text-center mb-12 text-green-400">My Recent Portfolio</h2> <div className="grid md:grid-cols-3 gap-8"> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-green-500 transition-all"> <h3 className="text-xl font-bold mb-2">📊 Data Management</h3> <p className="text-gray-400 text-sm">Complex Excel formatting and data cleaning projects.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-blue-500 transition-all"> <h3 className="text-xl font-bold mb-2">🌐 Web Solutions</h3> <p className="text-gray-400 text-sm">Modern & Responsive Next.js business websites.</p> </div> <div className="group relative overflow-hidden rounded-2xl bg-[#112240] p-6 border border-gray-800 hover:border-purple-500 transition-all"> <h3 className="text-xl font-bold mb-2">📄 File Conversion</h3> <p className="text-gray-400 text-sm">High-accuracy PDF to Word/Excel conversions.</p> </div> </div> </div> </section>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold inline-block">Order on Fiverr</a></div>
<div className="text-center my-4"><a href="https://www.fiverr.com/alihaidersandhu" target="_blank" className="bg-[#1dbf73] text-white px-8 py-3 rounded-lg font-bold shadow-md inline-block">Order on Fiverr</a></div>
<div className="text-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold">View Full Project (PDF)</a></div>
<div className="flex justify-center my-6"><a href="/specialist-work.pdf" target="_blank" className="bg-green-600 text-white px-8 py-3 rounded-lg font-bold shadow-lg hover:bg-green-700 transition-all">View Full Project (PDF)</a></div>
<a href="/specialist-work.pdf" target="_blank" style="display:block; text-align:center; padding:10px; background:green; color:white; border-radius:5px; margin:10px auto; width: fit-content;">View Full Project (PDF)</a>
      <footer className="bg-[#050d1a] py-12 border-t border-gray-800 text-center"> <div className="max-w-4xl mx-auto px-4"> <h3 className="text-xl font-bold text-green-400 mb-4">GlobalSkill.pk</h3> <p className="text-gray-400 mb-6">Expert Freelance Solutions | Data Entry | Crypto Analysis</p> <div className="flex justify-center gap-6 mb-8"> <a href="/training" className="text-gray-300 hover:text-white">Training</a> <a href="/pricing" className="text-gray-300 hover:text-white">Pricing</a> <a href="https://wa.me/923008609486" className="text-gray-300 hover:text-white">Contact</a> </div> <p className="text-sm text-gray-600">© 2026 GlobalSkill.pk - All Rights Reserved.</p> </div> </footer>
      <div className="fixed bottom-28 right-10 flex flex-col gap-4 z-50"> <a href="https://wa.me/923008609486?text=Hi%20Ali,%20I%20want%20to%20place%20an%20order" className="bg-blue-600 text-white px-6 py-2 rounded-full font-bold shadow-xl hover:bg-blue-700 transition-all flex items-center gap-2"> 🛒 Order Now </a> </div>
    </main>
  );
}
<a href="/specialist-work.pdf" target="_blank" className="text-green-400 underline mt-2 block text-center">View Full Project (PDF)</a>

export const PortfolioButton = () => (
  <div style={{textAlign: "center", margin: "20px"}}>
    <a href="/specialist-work.pdf" target="_blank" style={{background: "green", color: "white", padding: "10px 20px", borderRadius: "5px", textDecoration: "none"}}>View Full Project (PDF)</a>
  </div>
);
